info:
  app:
    name: identity-service
    description: Identity microservice
    version: 1.0
spring:
  application:
    name: identity-service
server:
  port: 9090
logging:
  level:
    org:
      springframework:
        web: DEBUG
